# Generated by Django 5.1.4 on 2026-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_special_case',
            field=models.BooleanField(default=False),
        ),
    ]
