# Generated by Django 5.1.4 on 2026-02-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0002_employee_is_external_employee_is_special_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
