# Generated by Django 5.1.4 on 2026-02-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0003_employee_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client_contract_work',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toggl_user_detail',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
    ]
