# Generated by Django 5.1.4 on 2026-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0004_client_is_external_client_contract_work_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
    ]
