# Generated by Django 5.1.4 on 2026-02-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0005_country_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtable',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buddy_email',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client_contract_employee',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contracted_employee',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file_category',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sheetrecord',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortworkemail',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work_category',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
    ]
