# Generated by Django 5.1.4 on 2026-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0007_client_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracted_hours',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contracted_hours',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_contract_employee',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_contract_work',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracted_employee',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toggl_user_detail',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_category',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
